### PR TITLE
Fix export issues

### PR DESCRIPTION
**Pull request by memelotsqui**
- [x] fix sparse accessors not being multiple of 4
- [x] fix issue cannot read properties of undefined in "isBone"
- [x] fix issue spring bones not dfinding root bones
- [x] fix issue some spring bones are being removed
- [x] fix issue colliders are note being exported

### CODE REVIEW

**Comment by madjin** [comment]
testing 291: https://cdn.discordapp.com/attachments/1041270464271622234/1174094857300611144/291_WIP.vrm?ex=6566580b&is=6553e30b&hm=198c42361d3e4c4e34db508fd59ac016d34fcdf20d88ba06d0bc1eba4376fcdd&
image
image
Screenshot from 2023-11-14 16-14-36

**Comment by madjin** [comment]
when I don't atlas textures
image

when I atlas the textures
image

**Comment by madjin** [comment]
Screenshot from 2023-11-14 18-36-47
Screenshot from 2023-11-14 18-36-12
https://cdn.discordapp.com/attachments/1041270464271622234/1174130752452042845/121_WIP2.vrm?ex=65667979&is=65540479&hm=858904e64004adbb09e09145315ef2a4c492177f4808ac5714d21c44cbb24233&
new errors

**Comment by memelotsqui** [comment]
for colliders to work we will also need this character-assets pr merged :)
https://github.com/M3-org/character-assets/pull/15

**Pull request merged**
